version: '3.8'

services:

   postgre:
      image: postgres:15.4
      container_name: postgre
      volumes:
         - ./database/data:/var/lib/postgresql/data
      environment:
         POSTGRES_USER: postgres
         POSTGRES_PASSWORD: postgres
      networks:
         - drf_postgres

   django:
      build: .
      image: django_blog
      container_name: django_blog
      volumes:
         - .:/app
         - static_volume:/app/static
         - files_volume:/app/files
      command: >
         sh -c "python manage.py migrate &&
                python manage.py collectstatic --no-input --clear &&
                gunicorn config.wsgi:application --bind 0.0.0.0:8000"
      networks:
         - drf_postgres
         - nginx_drf
      depends_on:
         - postgre

   nginx:
      image: nginx:1.25
      container_name: nginx_blog
      ports:
         - 80:80
      volumes:
         -  ./nginx:/etc/nginx/conf.d
         -  static_volume:/var/www/static
         -  files_volume:/var/www/files
      networks:
         - nginx_drf 
      depends_on:
         - django





volumes:
   drf:
      external: true

   static_volume:
      external: true

   files_volume:
      external: true


networks:
   drf_postgres:
      external: true
      driver: bridge
      name: drf_postgres

   nginx_drf:
      external: true
      driver: bridge
      name: nginx_drf



