version: '3.8'

services:

   postgre:
      image: postgres:15.4
      container_name: postgre
      volumes:
         - ./database/data:/var/lib/postgresql/data
      environment:
         POSTGRES_USER: postgres
         POSTGRES_PASSWORD: postgres
      networks:
         - blog_django_postgre

   django:
      build: .
      image: blog_django
      container_name: blog_django
      restart: always
      volumes:
         - .:/app
         - blog_static_volume:/app/static
         - blog_files_volume:/app/files
      command: >
         sh -c "python manage.py migrate &&
                python manage.py collectstatic --no-input --clear &&
                gunicorn config.wsgi:application --bind 0.0.0.0:8000"
      networks:
         - blog_django_postgre
         - blog_django_nginx
      depends_on:
         - postgre

   nginx:
      image: nginx:1.25
      container_name: blog_nginx
      ports:
         - 80:80
      volumes:
         -  ./nginx:/etc/nginx/conf.d
         -  blog_static_volume:/app/static
         -  blog_files_volume:/app/files
         # -  blog_static_volume:/var/www/static
         # -  blog_files_volume:/var/www/files
      networks:
         - blog_django_nginx
      depends_on:
         - django


volumes:
   drf:
      external: true

   blog_static_volume:
      external: true

   blog_files_volume:
      external: true


networks:
   blog_django_postgre:
      external: true
      driver: bridge
      name: blog_django_postgre

   blog_django_nginx:
      external: true
      driver: bridge
      name: blog_django_nginx



