version: '3.8'

services:

   nginx:
      container_name: nginx
      build: 
         context: ./config/nginx/
         dockerfile: Dockerfile
      image: drf_nginx
      ports:
         - 80:80
      volumes:
         - static_volume:/drf/static
         - files_volume:/drf/files
      networks:
         - nginx_drf 
      depends_on:
         - drf

   drf:
      build:
         context : .
         dockerfile : Dockerfile
      image: drf
      container_name: drf
      volumes:
         - .:/drf
         - static_volume:/drf/static
         - files_volume:/drf/files
      restart: always
      env_file: 
         - .env
      expose:
         - 8000
      networks:
         - drf_postgres
         - nginx_drf
      depends_on:
         - postgresql

   postgresql:
      image: postgres:15.4
      container_name: postgresql
      volumes:
         - ./database/data:/var/lib/postgresql/data
         # - drf:/var/lib/postgresql/data
      environment:
         POSTGRES_USER: postgres
         POSTGRES_PASSWORD: postgres
      expose:
         - 5432
      networks:
         - drf_postgres

volumes:
   drf:
      external: true

   static_volume:
      external: true

   files_volume:
      external: true


networks:
   drf_postgres:
      external: true
      driver: bridge
      name: drf_postgres

   nginx_drf:
      external: true
      driver: bridge
      name: nginx_drf



