version: '3.8'

services:

   postgresql:
      image: postgres:latest
      container_name: postgresql
      volumes:
         -  ./database/data:/var/lib/postgresql/data
      environment:
         POSTGRES_USER: postgres
         POSTGRES_PASSWORD: postgres
      ports:
         - 5432:5432
      networks:
         - net1


networks:
   net1:
      driver: bridge
      name: net