# Generated by Django 4.2.4 on 2023-12-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, null=True)),
                ('description', models.TextField(max_length=256, null=True)),
                ('situation', models.BooleanField(default=True)),
                ('views', models.IntegerField(default=True)),
                ('cover', models.ImageField(default=None, null=True, upload_to='courses/cover/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
