# Generated by Django 4.2.4 on 2023-12-26 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(max_length=256)),
                ('customer', models.CharField(max_length=128)),
                ('team', models.CharField(max_length=128)),
                ('cover', models.ImageField(upload_to='images/project_cover/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
