# Generated by Django 4.2.4 on 2023-12-29 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_article_slug_alter_article_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=256, null=True, unique=True),
        ),
    ]
